#!/usr/bin/env groovy

pipeline {
    agent any

    tools {
        jdk 'openjdk-11'
        maven 'maven-3.6.3'
    }

    stages {
        stage('test tool installation') {
            steps {
                echo "testing tool installation..."
                sh 'java -version'
                //sh 'which java'
                sh 'mvn -version'
                //sh 'which mvn'
            }
        }
        stage('source code checkout') {
            steps {
                echo "checking out code...."
                // clone code from GitHub repo
                git changelog: false, poll: false, url: 'https://github.com/Tom-Developer/simple-java-maven-app'
            }
        }
        stage('build') {
            steps {
                echo "building..."
                sh "mvn -Dmaven.test.failure.ignore=true clean verify"
            }

            post {
                // record the test results and archive the jar file.
                success {
                    junit '**/target/surefire-reports/TEST-*.xml'
                    archiveArtifacts 'target/*.jar'
                }
            }
        }
    }
}
